blank_issues_enabled: true
help_series: 
  - name: 📽 How To Uranium 📽
    link: COMING SOON
    about: Before creating an issue, please you watch the certain tutorial on the part you are strugguling on!