blank_issues_enabled: false
contact_links:
  - name: How to Uranium
    url: https://www.youtube.com/playlist?list=PLKGFv5F_wSIbWlhB16FPm3RuZ2apBC8e8
    about: Video series where you can learn all about Uranium