name: Bug report
description: >-
  Please use this template when you have encountered a bug in JEI.  
  If the issue seems to affect only one mod, please report to them first instead of here.
title: '[Bug]: '
body:
  - type: textarea
    id: repro_steps
    attributes:
      label: Steps to Reproduce the Bug
      description: Please explain what we need to do to cause the bug.
      placeholder: >-
        Example:  
        
        1. Hold Shift   
        2. Click the anvil in the JEI ingredient list on the left side.
    validations:
      required: true